### PR TITLE
feat: AWS xray tracing config

### PR DESCRIPTION
**Pull request by ReubenRobertsHEE**
TIS21-4226

### CODE REVIEW

**Comment by Judge40** [comment]
> No idea how to test this at this point :)

If you run the daemon locally you can see data in the AWS console.
There's some docker compose config floating around on slack, but I'm not sure if the fully fixed config is or not.

**Comment by Judge40** [comment]
Xray daemon config is now in the handbook

**Comment by ReubenRobertsHEE** [comment]
Juicy errors now!
```
2023-03-28T11:12:18.370+01:00  INFO 21764 --- [nio-8210-exec-4] u.n.h.t.t.c.api.VerifyResource           : Received callback for credential verification.
2023-03-28T11:12:18.375+01:00 ERROR 21764 --- [nio-8210-exec-4] c.a.x.s.LogErrorContextMissingStrategy   : Suppressing AWS X-Ray context missing exception (SegmentNotFoundException): Failed to begin subsegment named 'completeCredentialVerification': segment cannot be found.
2023-03-28T11:12:18.394+01:00 ERROR 21764 --- [nio-8210-exec-4] c.a.x.s.LogErrorContextMissingStrategy   : Suppressing AWS X-Ray context missing exception (SegmentNotFoundException): Failed to begin subsegment named 'getTokenClaims': segment cannot be found.
```

**Comment by ReubenRobertsHEE** [comment]
Ok cool, thanks for confirming @Judge40 . 

Given we are not going 'live' by any realistic measure for the next couple of months at least, shall we just park this piece of work and pick it up when Xray catches up with us? :)

**Review by DorisWongNHS — APPROVED** [review]

**Pull request merged**
