### PR TITLE
refactor: upgrade Spring Cloud AWS to 3.0.2

### PR DESCRIPTION
**Pull request by Judge40**
Version 3.x.x of Spring Cloud AWS is a complete rewrite and there are many changes from 2.x.x versions.

Delete the existing AmazonSqsConfig, auto-configuration can now take care of everything.
Replace the existing messaging dependencies with the single `spring-cloud-aws-starter-sqs`.
Set up an application-test.yml containing both the existing overrides, as well as disabling SQS. A static region must still be provided. Replace existing mocking and disabling of SQS for integration tests with a profile reference to the new app-test properties. Remove the `deletionPolicy` from `@SqsListener` annotation, the property has been removed and is now a configuration property. The default is `ON_SUCCESS`

TIS21-5115
TIS21-5133

### CODE REVIEW

**Comment by Judge40** [comment]
Created as a draft due to #118 also waiting for review

**Comment by ReubenRobertsHEE** [comment]
The changes seem sensible, but I am having a bit of trouble running the app locally. I'm getting a slew of
`Caused by: software.amazon.awssdk.services.sqs.model.SqsException: The address https://sqs.eu-west-2.amazonaws.com/ is not valid for this endpoint. (Service: Sqs, Status Code: 404, Request ID: ad4b97cb-bfb9-5bf8-8b89-ca566b7a3ef2)`
errors that I don't get running the main branch, all other environment context unchanged.
Have you bumped into this at all?

**Comment by Judge40** [comment]
> The changes seem sensible, but I am having a bit of trouble running the app locally. I'm getting a slew of `Caused by: software.amazon.awssdk.services.sqs.model.SqsException: The address https://sqs.eu-west-2.amazonaws.com/ is not valid for this endpoint. (Service: Sqs, Status Code: 404, Request ID: ad4b97cb-bfb9-5bf8-8b89-ca566b7a3ef2)` errors that I don't get running the main branch, all other environment context unchanged. Have you bumped into this at all?

I've got some issues running against localstack SQS queues, but pointing at real queues works fine for me.

**Comment by Judge40** [comment]
@ReubenRobertsHEE Do you use env vars or a credentials file for AWS creds?

**Comment by ReubenRobertsHEE** [comment]
I can also run against real queues no problem.

**Comment by ReubenRobertsHEE** [comment]
I've got both set up for AWS creds (not very DRY, I know 😁)

**Comment by Judge40** [comment]
I had I different issue because of a copy paste job. I've got the same error now, fixable by setting the app property `spring.cloud.aws.endpoint: http://localhost:4566`

**Comment by ReubenRobertsHEE** [comment]
> I had I different issue because of a bad copy paste job. I've got the same error now, fixable by setting the app property `spring.cloud.aws.endpoint: http://localhost:4566`

🏆 bingo, that fixes it!

**Review by ReubenRobertsHEE — APPROVED** [review]

**Comment by Judge40** [comment]
Merging this as-is, I'll work on making his easier to run locally separately.

**Pull request merged**
