### PR TITLE
feat: add fuzzy name matching during id checks

### PR DESCRIPTION
**Pull request by Judge40**
The identity checks rely on matching the forename and surname between TIS and the provided DSP credential. As there is a high percentage chance that names will mismatch between spelling mistakes and inclusive/exclusion of middle name, the name checking needs to be more forgiving.

Update the VerificationService to check the phonetic and text accuracies and make a decision based on the similarity rather than exact matching. Split names on spaces and hypens to allow matching when middle names, or double barrelled names are used.

Publish metrics for both phonetic and text accuracy to Cloudwatch to allow monitoring and ongoing improvements to be made to the level of fuzziness allowed.

TIS21-6065

### CODE REVIEW

**Comment by Judge40** [comment]
Converting to draft as I've missed some changes from the commit

**Comment by ReubenRobertsHEE** [comment]
I was wondering whether the cloudwatch metrics will make it easy to see what names were being compared when the closeness score is logged (and maybe the TIS id for the trainee as well)?

**Comment by Judge40** [comment]
> I was wondering whether the cloudwatch metrics will make it easy to see what names were being compared when the closeness score is logged (and maybe the TIS id for the trainee as well)?

We could use dimensions, but I'm not sure if it really fits. I don't think having the names available in cloudwatch is really that important though, it's more about whether we're (broadly) too lax or too strict.

There a definite argument for separating by first name and surname though.
Maybe a switch to metric names of `identity.accuracy.forenames` and `identity.accuracy.surname` with dimensions of `AccuracyType:text` and `AccuracyType:phonetic`.
It's hard to know when we don't actually have a reporting requirement, just trying to capture data for future needs.

**Comment by ReubenRobertsHEE** [comment]
Ok, that makes sense. I wonder if including a general log (maybe at debug level) of the names and outcome details would be useful though, to help identify any unexpected mis/matches?

**Comment by Judge40** [comment]
> Ok, that makes sense. I wonder if including a general log (maybe at debug level) of the names and outcome details would be useful though, to help identify any unexpected mis/matches?

I did intend to do that for failures 🙈 
I'll add a bit of debug logging.

**Review by ReubenRobertsHEE — APPROVED** [review]
LGTM

**Pull request merged**
